### ISSUE TITLE
Audio is not working

### ISSUE THREAD

**Issue by ashikxcel** [pedroSG94/Stream-USB-test#3]
Im using this library for streaming to youtube with external camera. Its working but audio is not streaming. Will it stream audio from Mobile microphone or external camera?

**Comment by osokindm** [comment]
Hello, i know it's been a long time ago, but did you manage to make audio work back then?

**Comment by pedroSG94** [comment]
Hello,

Currently, you can use the app example of the RootEncoder project and change the video source to usb using the rotation activity example.
That example supports audio using the  microphone

**Comment by osokindm** [comment]
Thank you, but I can't use rotation activity example with usb camera. Every time I switch video source from phone camera to CameraUVC I get no image from usb camera. Moreover camera is not being opened.
However, [original uvc lib](https://github.com/shiyinghan/UVCAndroid) demo is working fine. 

I have found this error in logs: `[21030*UVCPreview.cpp:546:prepare_preview]:could not negotiate with camera:err=-51`

I will try to find the fix, but any help is very appreciated.

**Comment by pedroSG94** [comment]
> I have found this error in logs: `[21030*UVCPreview.cpp:546:prepare_preview]:could not negotiate with camera:err=-51`

Can you see the dialog after connect the UVC camera using the rotation example?
Did you tried remove this line?
https://github.com/pedroSG94/RootEncoder/blob/master/extra-sources/src/main/java/com/pedro/extrasources/CameraUvcSource.kt#L82

**Comment by osokindm** [comment]
Wow! Removing this line worked, thank you very much!

**Comment by osokindm** [comment]
So the problem was wrong resolution in preview window? And camera could not start because of it?

**Comment by pedroSG94** [comment]
Yes, maybe your camera doesn't support the resolution selected. 
Can you try fix the method that select the resolution? I'm not able to reproduce it

**Comment by osokindm** [comment]
I will try but can't promise
What i have found out is that by the time we want to set resolution `cameraHelper?.previewSize` already has  a value. Is it supposed to be so? 
And it only works with Size(1920x1080@30,type:7), any other value makes the app non-working. 
logitech b525
![image](https://github.com/user-attachments/assets/21b878d1-a973-496e-b8ff-e8b52955ec36)

**Comment by pedroSG94** [comment]
Hello,

Ok, let me know if you are not able to fix it and I will remove that lines to avoid this error in the next release version.
